apps:
  - script : "bin/www"
    name   : 'bomblab-wechat'
    log_date_format : "YYYY-MM-DD HH:mm:ss.SSS"
    error_file : "./log/main_err.log"
    out_file : "./log/main_std.log"
    merge_logs : true
    instances : 2
    exec_mode  : "cluster"

  - script : "subscribe_timer.js"
    name : "bomblab-subscribe-timer"
    error_file : "./log/subscribe_err.log"
    out_file : "./log/subscribe_std.log"
    merge_logs : true
    log_date_format : "YYYY-MM-DD HH:mm:ss.SSS"

  - script : "tpl_sender.js"
    name : "bomblab-tpl-sender"
    error_file : "./log/tpl_sender_err.log"
    out_file : "./log/tpl_sender_std.log"
    merge_logs : true
    log_date_format : "YYYY-MM-DD HH:mm:ss.SSS"
